### PR TITLE
When noEmptyTranslation is true, missing keys are added with the key …

### PR DESCRIPTION
**Pull request by vricosti**
…as default translation.
Added an option to generate missing keys with a default translation (key itself)

### CODE REVIEW

**Comment by Spittal** [comment]
Hey! looks great, but we're looking for a unit test for this functionality to be added please!

**Comment by Spittal** [comment]
Hmm I also wonder if this should be the default behaviour of `--add`? I sort of feel like it makes the most sense to just do this by default. What do you think @pixari and @vricosti ?

**Comment by guillaume-gagnaire** [comment]
Any ETA for this feature ? It's really useful when used in conjunction with VSCode Auto-translate plugin :)

**Comment by gunta** [comment]
+1

**Comment by Spittal** [comment]
Hey @vricosti I would like to add this in, but I hesitate to do so without a proper unit test

**Comment by wilsenhc** [comment]
Opened #165 with changes to this PR @Spittal @vricosti

**Pull request merged**
